# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2bb6639c11e8da72e38d6e2d29aa47ef5d434a8879d391c6405dda3fbc2d8d008653610861165303e67b7cc1ed1b0446e71e50e484d05588ad213096511c500

test:
  secret_key_base: 8b56c22dbb54b1ea883b0dd5c9a8ecc327828450647526398a2808d726d1dda4ace88d5590f4db45e9e0c9f1e73242b0a92f6abfed38e3ce9e747c0f06183082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
